### PR TITLE
Fix the Radio PR

### PR DESCRIPTION
**Pull request by mcm001**

### CODE REVIEW

**Comment by mcm001** [comment]
This PR fixes note blocks and headings, and should address all modifications requested to the original PR.

**Comment by mcm001** [comment]
(I did this on mobile so let me know if the PR targets the correct branch, I’ll check when I get back home to make sure.)

**Comment by Daltz333** [comment]
@mcm001 Please retarget develop

**Comment by mcm001** [comment]
@Daltz333 I've done that and also pulled from upstream testing so it's up to date

**Comment by Daltz333** [comment]
I have no idea. It may be better to just branch off of the latest develop, and just manually copy your changes in.

**Pull request merged**
